// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.
package i18n

import (
	"embed"
	"fmt"
	"path/filepath"

	"github.com/goccy/go-json"
)

//go:embed lang/*.json
var translationsFS embed.FS
var translations map[string]string

func init() {
	translations = make(map[string]string)
	lang := GetLang()
	if lang == langCodeEN {
		return
	}
	langPath := filepath.Join(langDir, fmt.Sprintf("%s.json", lang))
	var langData []byte
	var err error
	langData, err = translationsFS.ReadFile(langPath)
	if err != nil {
		return
	}
	var langTranslations map[string]string
	if err = json.Unmarshal(langData, &langTranslations); err != nil {
		return
	}
	for key, value := range langTranslations {
		translations[key] = value
	}
}
