//go:build !wasip1

// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.
package http

// StopListenerByID останавливает HTTP сервер, закрывая listener по его ID.
// В не-WASM окружении не реализовано, так как listener не используется.
func StopListenerByID(listenerID uint64) (err error) {

	// В не-WASM окружении listener не используется, поэтому остановка не требуется
	return
}
