//go:build wasip1

// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.
package http

import (
	"net/http"

	"tgp/core/net"
)

// ListenAndServe запускает HTTP сервер на указанном адресе.
func ListenAndServe(addr string, handler http.Handler) (err error) {

	listener, err := net.Listen(net.NetworkTCP, addr)
	if err != nil {
		return err
	}
	defer listener.Close()

	// Используем стандартную http.Serve, которая делает цикл Accept() и обработку соединений
	return http.Serve(listener, handler)
}
