//go:build wasip1

// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.
package http

import (
	"log/slog"

	"tgp/core/net"
)

// StopListenerByID останавливает HTTP сервер, закрывая listener по его ID.
func StopListenerByID(listenerID uint64) (err error) {

	// Удаляем connectionHandler для этого listener
	net.RemoveConnectionHandler(listenerID)

	// Закрываем listener, что остановит цикл Accept() на хосте
	if err = net.CloseListenerByID(listenerID); err != nil {
		slog.Error("StopListenerByID: failed to close listener", "listenerID", listenerID, "error", err)
		return
	}
	slog.Debug("StopListenerByID: listener has been stopped", "listenerID", listenerID)
	return
}
