//go:build !wasip1

// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.
package http

import (
	"log/slog"
	"net/http"
)

// ListenerServeStart запускает HTTP сервер асинхронно.
// Неблокирующая функция - возвращает управление сразу после запуска.
// В не-WASM окружении аналогична ListenAndServe.
// Возвращает listenerID (в не-WASM окружении всегда 0, так как listener не используется).
func ListenerServeStart(addr string, handler http.Handler) (listenerID uint64, err error) {

	// Запускаем сервер в отдельной горутине (неблокирующая)
	go func() {
		if serveErr := http.ListenAndServe(addr, handler); serveErr != nil {
			slog.Error("ListenerServeStart: server error", "address", addr, "error", serveErr)
		}
	}()

	// В не-WASM окружении listenerID не используется, возвращаем 0
	return 0, nil
}
