// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.
package manifest

import (
	"encoding/json"
	"fmt"
	"os"

	"tgp/core/plugin"
)

// GenerateManifest генерирует plugin.json файл из plugin.Info.
func GenerateManifest(pluginInstance plugin.Plugin, outputPath string) (err error) {
	info, err := pluginInstance.Info()
	if err != nil {
		return fmt.Errorf("failed to get plugin info: %w", err)
	}
	manifest := Manifest{
		Name:         info.Name,
		Description:  info.Description,
		Author:       info.Author,
		License:      info.License,
		Dependencies: info.Dependencies,
	}
	manifestJSON, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to marshal manifest: %w", err)
	}
	manifestJSON = append(manifestJSON, '\n')
	if err = os.WriteFile(outputPath, manifestJSON, 0600); err != nil {
		return fmt.Errorf("failed to write manifest file: %w", err)
	}
	return nil
}
