//go:build wasip1

// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.
package net

import (
	"fmt"

	"tgp/core/wasm"
)

// CloseListenerByID закрывает listener по его ID.
func CloseListenerByID(listenerID uint64) (err error) {

	// Вызываем host функцию для закрытия listener
	ret := listener_close(listenerID)

	// Обрабатываем ошибку
	if err = wasm.HandleHostError(ret); err != nil {
		return fmt.Errorf("failed to close listener %d: %w", listenerID, err)
	}

	return nil
}
